apiVersion: v1
kind: Secret
metadata:
  name: notes-secret
  namespace: notes-app
type: Opaque
stringData:
  DB_CONNECTION: pg
  DB_DATABASE: notesdb
  DB_HOST: svcnotes
  DB_PASSWORD: notes
  DB_PORT: '5432'
  DB_USER: notes
